apiVersion: v2
name: prometheus-pve-exporter
description: A Helm chart to export the metrics from pve in Prometheus format.
version: 0.1.4
appVersion: "2.2.3"
keywords:
- pve-exporter
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/mahahe-it/helm
    - name: Upstream Project
      url: https://github.com/prometheus-pve/prometheus-pve-exporter
maintainers:
  - email: matteob99@mahahe.it
    name: MatteoB99
  - email: haloghen@mahahe.it
    name: Haloghen
engine: gotpl
home: https://github.com/prometheus-pve/prometheus-pve-exporter
sources:
  - https://github.com/prometheus-pve/prometheus-pve-exporter
  - https://github.com/mahahe-it/helm/tree/master/charts/
